### PR TITLE
Expose Element's ability to get properties

### PR DESCRIPTION
**Pull request by illicitonion**

### CODE REVIEW

**Comment by fluffysquirrels** [comment]
This looks great!

As with the other PR, can you try and add an integration test?

**Comment by fluffysquirrels** [comment]
I'm on my phone so can't easily check whether this will merge cleanly with the updated master. Would you rebase and add a test in the style of your new overhauled integration tests?

**Comment by illicitonion** [comment]
Rebased, added test :) Thanks!

**Comment by fluffysquirrels** [comment]
The test looks good. As I mentioned elsewhere, would you mind looking at the build failures?

**Pull request merged**
