### PR TITLE
Support for other browsers

### PR DESCRIPTION
**Pull request by equalsraf**
Hi, I've been looking into using this with other browsers

- some implementations (webdriver, chrome) will not create a session if the client sends a null in the capabilities attribute
- Added the necessary types for the chrome driver
- By default chromedriver is not compatible with the w3c webdriver spec - but one can enable compatibility with a capability extension field
- I've added a commit for a verbose flag to `www` just because it makes debugging easier

I also tried to test with other implementations, but failed for unrelated reasons

- operadriver, should to be based on chromedriver, but it did not work for me because of [this issue upstream](https://github.com/operasoftware/operachromiumdriver/issues/9)
- the webkitgtk driver crashed on me

Other than that I've added tests using the chrome driver, but it took some fiddling with travis likely because of [this issue in travis](https://github.com/travis-ci/travis-ci/issues/7150)

### CODE REVIEW

**Comment by equalsraf** [comment]
For completeness, it is possible to request w3c compliance from chrome ([issue](https://bugs.chromium.org/p/chromedriver/issues/detail?id=1942)) and it works e.g.

```diff
diff --git a/src/lib.rs b/src/lib.rs
index 88e7a80..8747747 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -16,6 +16,7 @@ extern crate serde;
 use serde::Serialize;
 use serde::de::DeserializeOwned;
 
+#[macro_use]
 extern crate serde_json;
 pub use serde_json::Value as JsonValue;
 
diff --git a/src/messages.rs b/src/messages.rs
index d27cd16..d17b321 100644
--- a/src/messages.rs
+++ b/src/messages.rs
@@ -43,7 +43,14 @@ pub struct NewSessionCmd {
 impl NewSessionCmd {
     pub fn new() -> Self {
         NewSessionCmd {
-            capabilities: JsonValue::Object(Map::new()),
+            capabilities: json!({
+                "alwaysMatch": {
+                    // ask chrome to be w3c compliant
+                    "chromeOptions": {
+                        "w3c": true
+                    }
+                }
+            }),
             desiredCapabilities: JsonValue::Object(Map::new()),
         }
     }
```

But I was unable to trigger this without simultaneously breaking geckodriver.

**Comment by equalsraf** [comment]
Nevermind I figured it out, the capability name was wrong.

**Comment by fluffysquirrels** [comment]
This looks like great progress! On my phone now but I'll take a look at the diffs later.

**Comment by fluffysquirrels** [comment]
This is really good work, I'd like to support other browsers, especially Chrome. Opera and webkitgtk sound nice, but could be added later. I think I put a note in README.md or lib.rs about browser support, that will need updating when ChromeDriver goes in.

A few suggestions for you here. Please feel free to give alternatives.

**Comment by equalsraf** [comment]
Ok I've moved all of the travis bits to #14. I think i covered all you comments, except the one about avoiding the 'goog:chromeOptions' in the session cmd constructor.

BTW github seems to hide away the comments made in a commit when I rebased, original links for the commits and comments

- https://github.com/fluffysquirrels/webdriver_client_rust/commit/66414dd9df45c971a00fa0f37f5d83822127682d
- https://github.com/fluffysquirrels/webdriver_client_rust/commit/11aedcf2ff8c6894583b8f5a28febcdc1681a484
- https://github.com/fluffysquirrels/webdriver_client_rust/commit/2dcb34be29d592ab4e87fc80a6039aa97ef10bd3
- https://github.com/fluffysquirrels/webdriver_client_rust/commit/3ddf5a6a52d66c6881f861fc9a88d27ea6db42fe
- https://github.com/fluffysquirrels/webdriver_client_rust/commit/bb64f9ee462b61d719b30cc8d2e25423d042b669

**Comment by fluffysquirrels** [comment]
This looks great, very happy for it to be merged.

Wow, github hiding those previous comments when you rebase is incredibly annoying, I've not noticed how bad it was before. What I'd expect is a new entry to show up with the old commits greyed out or something.

**Comment by fluffysquirrels** [comment]
I created #16 "Consider refactoring browser-specific capabilities on creating a new session" to discuss the 'goog:chromeOptions' in the session cmd constructor.

**Pull request merged**
