### PR TITLE
Expose Element's ability to find children

### PR DESCRIPTION
**Pull request by illicitonion**

### CODE REVIEW

**Comment by fluffysquirrels** [comment]
This looks great!

Any chance you could add a quick test to tests/webdriver_client_integration.rs in test fn test_file()? If you have Firefox installed to "/usr/bin/firefox" it should just run with cargo test. Hmmm, I should document this.

**Comment by fluffysquirrels** [comment]
I'm on my phone so can't easily check whether this will merge cleanly with the updated master. Would you rebase and add a test in the style of your new overhauled integration tests?

**Comment by illicitonion** [comment]
Rebased, added test :) Thanks!

**Comment by fluffysquirrels** [comment]
The test looks good. I think the build might have started breaking after your test overhaul commit, though. Would you mind looking at [#12: Fix the build](#12)? I can help if you can't or you get stuck.

**Pull request merged**
