### PR TITLE
add possibility for custom driver paths and add `default()`

### PR DESCRIPTION
**Pull request by cuechan**
ff's and chrome's DriverBuilder constructor `new()` now takes the path to the driver as an argument. When using `default()` it is assumed that the driver is in `$PATH`.
With this it is not necessary to move the drivers to a systems directory or start the program with some sort of `PATH="$PATH:./"`.

### CODE REVIEW

**Comment by fluffysquirrels** [comment]
Hi! I really like this new feature.

Your change breaks any current code that calls the `DriverBuilder::new()` constructor without arguments. How about leaving the existing constructor as it is and adding a setter on the `DriverBuilder` called `driver_path()`, similar to the existing `port()` and `kill_on_drop()` setters?

**Comment by cuechan** [comment]
Thanks for your reply. 
Yes that make sense but on the other hand, the driver binary is an essential part of the `DriverBuilder`. So I think it would make sense to pass the path as an arg to the constructor and use `default()` as a shortcut. AFAIK crates.io is keeping old versions, so existing code would not break.
For me, both ways would be alright :D

I am not sure why travis is failing. For some reason only [a few tests](https://travis-ci.org/fluffysquirrels/webdriver_client_rust/jobs/378924367#L819)  failed and only with `stable`.
I will add `RUST_BACKTRACE=1` to travis' environment. I hope you don't mind :)

**Comment by fluffysquirrels** [comment]
`RUST_BACKTRACE=1` is good, thanks!

Even for required parameters I'd prefer to use a builder for clarity; I hate opaque argument lists of required arguments. For driver path I'd argue we have a semi-sensible default, but you're right driver path is pretty key.

> AFAIK crates.io is keeping old versions, so existing code would not break.
True, but I really like to avoid breaking changes. This is another reason I like the builder pattern.

Thanks a lot for making the changes.

**Comment by fluffysquirrels** [comment]
Looks good to me! Thanks so much for your contribution!

**Pull request merged**
